# Generated by Django 4.0.5 on 2022-06-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Token', '0002_license_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='paid',
        ),
        migrations.AddField(
            model_name='account',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
