# Generated by Django 4.0.5 on 2022-06-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Token', '0003_remove_license_paid_account_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='website',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
